language: minimal

services:
    - docker

before_install:
    - touch .env.test.local
    - echo "DEBRICKED_USERNAME=$username" >> .env.test.local
    - echo "DEBRICKED_PASSWORD=$password" >> .env.test.local
    - docker build -t php-test .

script:
    - docker run php-test --env-file ./.env.test.local