language: minimal

services:
    - docker

before_install:
    - touch .env.test.local
    - echo "DEBRICKED_USERNAME=$username" >> .env.test.local
    - echo "DEBRICKED_PASSWORD=$password" >> .env.test.local
    - docker build --target=test -t php-test .

script:
    - travis_wait 30 docker run --env-file ./.env.test.local php-test
